# add plugins...
gems: ['jekyll-paginate', 'jemoji']

# exclude some build files
exclude: ['Gemfile*', 'Guardfile', 'scss', 'README.md', '.gitignore']

# interpretter
markdown: kramdown

# basic config
permalink: /:title
destination: ./public

# pagination
paginate: 10
paginate_path: "page:num"

# site details
title: 'Fifty-Two Weeks'
description: 'Andrew Gallagher, aka. Kivlor. Software Developer, Gamer, Woodworker and Geek.'
author: 'kivlor'