# exclude some build files
exclude: ['Gemfile*', 'Guardfile', 'scss', 'README.md', '.gitignore']

# basic config
permalink: /:title
destination: ./public

# pagination
paginate: 10
paginate_path: "page:num"

# site details
title: 'Fifty-Two Weeks'
author: 'kivlor'

# extra gems
gems:
  - jemoji